import { AutoCompleteComponent } from '@syncfusion/ej2-react-dropdowns';
import * as React from 'react';
import { useStateContext } from '../contexts/ContextProvider';
import * as ReactDOM from 'react-dom';
import "./Search.css"

const Search = () => {

    let searchData = [
        { StockName: 'Apple Inc.', Code: 'AAPL' },
        { StockName: 'AAPL', Code: 'AAPL' },
        { StockName: 'Microsoft Corporation', Code: 'MSFT' },
        { StockName: 'MSFT', Code: 'MSFT' },
        { StockName: 'Amazon.com Inc.', Code: 'AMZN' },
        { StockName: 'AMZN', Code: 'AMZN' },
        { StockName: 'Tesla Inc', Code: 'TSLA' },
        { StockName: 'TSLA', Code: 'TSLA' },
        { StockName: 'Alphabet Inc. Class A', Code: 'GOOGL' },
        { StockName: 'GOOGL', Code: 'GOOGL' },
        { StockName: 'Alphabet Inc. Class C', Code: 'GOOG' },
        { StockName: 'GOOG', Code: 'GOOG' },
        { StockName: 'Berkshire Hathaway Inc. Class B', Code: 'BRK.B' },
        { StockName: 'BRK.B', Code: 'BRK.B' },
        { StockName: 'UnitedHealth Group Incorporated', Code: 'UNH' },
        { StockName: 'UNH', Code: 'UNH' },
        { StockName: 'Johnson & Johnson', Code: 'JNJ' },
        { StockName: 'JNJ', Code: 'JNJ' },
        { StockName: 'Exxon Mobil Corporation', Code: 'XOM' },
        { StockName: 'XOM', Code: 'XOM' },
        { StockName: 'JPMorgan Chase & Co.', Code: 'JPM' },
        { StockName: 'JPM', Code: 'JPM' },
        { StockName: 'Procter & Gamble Company', Code: 'PG' },
        { StockName: 'PG', Code: 'PG' },
        { StockName: 'Meta Platforms Inc. Class A', Code: 'META' },
        { StockName: 'META', Code: 'META' },
        { StockName: 'NVIDIA Corporation', Code: 'NVDA' },
        { StockName: 'NVDA', Code: 'NVDA' },
        { StockName: 'Visa Inc. Class A', Code: 'V' },
        { StockName: 'V', Code: 'V' },
        { StockName: 'Chevron Corporation', Code: 'CVX' },
        { StockName: 'CVX', Code: 'CVX' },
        { StockName: 'Home Depot Inc.', Code: 'HD' },
        { StockName: 'HD', Code: 'HD' },
        { StockName: 'Mastercard Incorporated Class A', Code: 'MA' },
        { StockName: 'MA', Code: 'MA' },
        { StockName: 'AbbVie Inc.', Code: 'ABBV' }, { StockName: 'ABBV', Code: 'ABBV' },
        { StockName: 'Pfizer Inc.', Code: 'PFE' },
        { StockName: 'PFE', Code: 'PFE' },
        { StockName: 'Eli Lilly and Company', Code: 'LLY' },
        { StockName: 'LLY', Code: 'LLY' },
        { StockName: 'PepsiCo Inc.', Code: 'PEP' }, { StockName: 'PEP', Code: 'PEP' },
        { StockName: 'Coca-Cola Company', Code: 'KO' },
        { StockName: 'KO', Code: 'KO' }, { StockName: 'Bank of America Corp', Code: 'BAC' },
        { StockName: 'BAC', Code: 'BAC' },
        { StockName: 'Merck & Co. Inc.', Code: 'MRK' },
        { StockName: 'MRK', Code: 'MRK' }, { StockName: 'Costco Wholesale Corporation', Code: 'COST' },
        { StockName: 'COST', Code: 'COST' },
        { StockName: 'Thermo Fisher Scientific Inc.', Code: 'TMO' },
        { StockName: 'TMO', Code: 'TMO' },
        { StockName: 'Broadcom Inc.', Code: 'AVGO' },
        { StockName: 'AVGO', Code: 'AVGO' }, { StockName: 'Walmart Inc.', Code: 'WMT' }, { StockName: 'WMT', Code: 'WMT' }, { StockName: 'Walt Disney Company', Code: 'DIS' }, { StockName: 'DIS', Code: 'DIS' },
        { StockName: 'McDonald\'s Corporation', Code: 'MCD' },
        { StockName: 'MCD', Code: 'MCD' },
        { StockName: 'Abbott Laboratories', Code: 'ABT' },
        { StockName: 'ABT', Code: 'ABT' },
        { StockName: 'Danaher Corporation', Code: 'DHR' },
        { StockName: 'DHR', Code: 'DHR' },
        { StockName: 'Cisco Systems Inc.', Code: 'CSCO' },
        { StockName: 'CSCO', Code: 'CSCO' },
        { StockName: 'Verizon Communications Inc.', Code: 'VZ' },
        { StockName: 'VZ', Code: 'VZ' },
        { StockName: 'Accenture Plc Class A', Code: 'ACN' },
        { StockName: 'ACN', Code: 'ACN' },
        { StockName: 'NextEra Energy Inc.', Code: 'NEE' },
        { StockName: 'NEE', Code: 'NEE' },
        { StockName: 'Wells Fargo & Company', Code: 'WFC' },
        { StockName: 'WFC', Code: 'WFC' },
        { StockName: 'Bristol-Myers Squibb Company', Code: 'BMY' },
        { StockName: 'BMY', Code: 'BMY' },
        { StockName: 'Salesforce Inc.', Code: 'CRM' },
        { StockName: 'CRM', Code: 'CRM' },
        { StockName: 'Texas Instruments Incorporated', Code: 'TXN' },
        { StockName: 'TXN', Code: 'TXN' },
        { StockName: 'Philip Morris International Inc.', Code: 'PM' },
        { StockName: 'PM', Code: 'PM' },
        { StockName: 'Comcast Corporation Class A', Code: 'CMCSA' },
        { StockName: 'CMCSA', Code: 'CMCSA' },
        { StockName: 'ConocoPhillips', Code: 'COP' },
        { StockName: 'COP', Code: 'COP' },
        { StockName: 'QUALCOMM Incorporated', Code: 'QCOM' },
        { StockName: 'QCOM', Code: 'QCOM' },
        { StockName: 'Linde plc', Code: 'LIN' }, { StockName: 'LIN', Code: 'LIN' },
        { StockName: 'Adobe Incorporated', Code: 'ADBE' }, { StockName: 'ADBE', Code: 'ADBE' },
        { StockName: 'CVS Health Corporation', Code: 'CVS' },
        { StockName: 'CVS', Code: 'CVS' }, { StockName: 'Union Pacific Corporation', Code: 'UNP' },
        { StockName: 'UNP', Code: 'UNP' },
        { StockName: 'NIKE Inc. Class B', Code: 'NKE' },
        { StockName: 'NKE', Code: 'NKE' }, { StockName: 'Raytheon Technologies Corporation', Code: 'RTX' }, { StockName: 'RTX', Code: 'RTX' }, { StockName: 'United Parcel Service Inc. Class B', Code: 'UPS' },
        { StockName: 'UPS', Code: 'UPS' },
        { StockName: 'Amgen Inc.', Code: 'AMGN' },
        { StockName: 'AMGN', Code: 'AMGN' },
        { StockName: 'Lowe\'s Companies Inc.', Code: 'LOW' },
        { StockName: 'LOW', Code: 'LOW' },
        { StockName: 'Honeywell International Inc.', Code: 'HON' },
        { StockName: 'HON', Code: 'HON' },
        { StockName: 'AT&T Inc.', Code: 'T' },
        { StockName: 'T', Code: 'T' },
        { StockName: 'Intel Corporation', Code: 'INTC' },
        { StockName: 'INTC', Code: 'INTC' },
        { StockName: 'Morgan Stanley', Code: 'MS' },
        { StockName: 'MS', Code: 'MS' },
        { StockName: 'International Business Machines Corporation', Code: 'IBM' }, { StockName: 'IBM', Code: 'IBM' },
        { StockName: 'Advanced Micro Devices Inc.', Code: 'AMD' },
        { StockName: 'AMD', Code: 'AMD' }, { StockName: 'Intuit Inc.', Code: 'INTU' }, { StockName: 'INTU', Code: 'INTU' },
        { StockName: 'Elevance Health Inc.', Code: 'ELV' }, { StockName: 'ELV', Code: 'ELV' },
        { StockName: 'Medtronic Plc', Code: 'MDT' },
        { StockName: 'MDT', Code: 'MDT' },
        { StockName: 'Charles Schwab Corp', Code: 'SCHW' },
        { StockName: 'SCHW', Code: 'SCHW' },
        { StockName: 'S&P Global Inc.', Code: 'SPGI' },
        { StockName: 'SPGI', Code: 'SPGI' },
        { StockName: 'American Tower Corporation', Code: 'AMT' }, { StockName: 'AMT', Code: 'AMT' }, { StockName: 'Goldman Sachs Group Inc.', Code: 'GS' }, { StockName: 'GS', Code: 'GS' }, { StockName: 'Netflix Inc.', Code: 'NFLX' }, { StockName: 'NFLX', Code: 'NFLX' }, { StockName: 'PayPal Holdings Inc.', Code: 'PYPL' },
        { StockName: 'PYPL', Code: 'PYPL' }, { StockName: 'Oracle Corporation', Code: 'ORCL' }, { StockName: 'ORCL', Code: 'ORCL' }, { StockName: 'Lockheed Martin Corporation', Code: 'LMT' }, { StockName: 'LMT', Code: 'LMT' },
        { StockName: 'Starbucks Corporation', Code: 'SBUX' },
        { StockName: 'SBUX', Code: 'SBUX' }, { StockName: 'Deere & Company', Code: 'DE' },
        { StockName: 'DE', Code: 'DE' },
        { StockName: 'Automatic Data Processing Inc.', Code: 'ADP' }, { StockName: 'ADP', Code: 'ADP' }, { StockName: 'BlackRock Inc.', Code: 'BLK' }, { StockName: 'BLK', Code: 'BLK' }, { StockName: 'Caterpillar Inc.', Code: 'CAT' }, { StockName: 'CAT', Code: 'CAT' }, { StockName: 'Citigroup Inc.', Code: 'C' }, { StockName: 'C', Code: 'C' }, { StockName: 'Cigna Corporation', Code: 'CI' },
        { StockName: 'CI', Code: 'CI' },
        { StockName: 'American Express Company', Code: 'AXP' },
        { StockName: 'AXP', Code: 'AXP' },
        { StockName: 'Mondelez International Inc. Class A', Code: 'MDLZ' }, { StockName: 'MDLZ', Code: 'MDLZ' }, { StockName: 'T-Mobile US Inc.', Code: 'TMUS' }, { StockName: 'TMUS', Code: 'TMUS' }, { StockName: 'Southern Company', Code: 'SO' }, { StockName: 'SO', Code: 'SO' },
        { StockName: 'Prologis Inc.', Code: 'PLD' }, { StockName: 'PLD', Code: 'PLD' },
        { StockName: 'Duke Energy Corporation', Code: 'DUK' }, { StockName: 'DUK', Code: 'DUK' }, { StockName: 'Gilead Sciences Inc.', Code: 'GILD' },
        { StockName: 'GILD', Code: 'GILD' }, { StockName: 'ServiceNow Inc.', Code: 'NOW' }, { StockName: 'NOW', Code: 'NOW' }, { StockName: 'Altria Group Inc', Code: 'MO' },
        { StockName: 'MO', Code: 'MO' }, { StockName: 'Boeing Company', Code: 'BA' }, { StockName: 'BA', Code: 'BA' },
        { StockName: 'Analog Devices Inc.', Code: 'ADI' },
        { StockName: 'ADI', Code: 'ADI' },
        { StockName: 'Chubb Limited', Code: 'CB' }, { StockName: 'CB', Code: 'CB' }, { StockName: 'Marsh & McLennan Companies Inc.', Code: 'MMC' }, { StockName: 'MMC', Code: 'MMC' }, { StockName: 'Regeneron Pharmaceuticals Inc.', Code: 'REGN' }, { StockName: 'REGN', Code: 'REGN' },
        { StockName: 'Applied Materials Inc.', Code: 'AMAT' },
        { StockName: 'AMAT', Code: 'AMAT' },
        { StockName: 'Vertex Pharmaceuticals Incorporated', Code: 'VRTX' }, { StockName: 'VRTX', Code: 'VRTX' }, { StockName: 'TJX Companies Inc', Code: 'TJX' }, { StockName: 'TJX', Code: 'TJX' }, { StockName: 'Northrop Grumman Corp.', Code: 'NOC' }, { StockName: 'NOC', Code: 'NOC' }, { StockName: 'General Electric Company', Code: 'GE' },
        { StockName: 'GE', Code: 'GE' },
        { StockName: 'Progressive Corporation', Code: 'PGR' },
        { StockName: 'PGR', Code: 'PGR' }, { StockName: 'Target Corporation', Code: 'TGT' },
        { StockName: 'TGT', Code: 'TGT' },
        { StockName: 'Stryker Corporation', Code: 'SYK' }, { StockName: 'SYK', Code: 'SYK' }, { StockName: 'Zoetis Inc. Class A', Code: 'ZTS' }, { StockName: 'ZTS', Code: 'ZTS' }, { StockName: 'EOG Resources Inc.', Code: 'EOG' }, { StockName: 'EOG', Code: 'EOG' },
        { StockName: 'Intuitive Surgical Inc.', Code: 'ISRG' }, { StockName: 'ISRG', Code: 'ISRG' }, { StockName: 'Booking Holdings Inc.', Code: 'BKNG' }, { StockName: 'BKNG', Code: 'BKNG' }, { StockName: 'Crown Castle Inc.', Code: 'CCI' }, { StockName: 'CCI', Code: 'CCI' }, { StockName: 'Becton Dickinson and Company', Code: 'BDX' },
        { StockName: 'BDX', Code: 'BDX' },
        { StockName: 'CME Group Inc. Class A', Code: 'CME' },
        { StockName: 'CME', Code: 'CME' },
        { StockName: 'Dominion Energy Inc', Code: 'D' },
        { StockName: 'D', Code: 'D' },
        { StockName: 'PNC Financial Services Group Inc.', Code: 'PNC' }, { StockName: 'PNC', Code: 'PNC' },
        { StockName: 'Fiserv Inc.', Code: 'FISV' }, { StockName: 'FISV', Code: 'FISV' },
        { StockName: '3M Company', Code: 'MMM' }, { StockName: 'MMM', Code: 'MMM' },
        { StockName: 'Colgate-Palmolive Company', Code: 'CL' },
        { StockName: 'CL', Code: 'CL' },
        { StockName: 'Waste Management Inc.', Code: 'WM' },
        { StockName: 'WM', Code: 'WM' },
        { StockName: 'Humana Inc.', Code: 'HUM' },
        { StockName: 'HUM', Code: 'HUM' },
        { StockName: 'CSX Corporation', Code: 'CSX' },
        { StockName: 'CSX', Code: 'CSX' },
        { StockName: 'Truist Financial Corporation', Code: 'TFC' },
        { StockName: 'TFC', Code: 'TFC' },
        { StockName: 'U.S. Bancorp', Code: 'USB' },
        { StockName: 'USB', Code: 'USB' },
        { StockName: 'Aon Plc Class A', Code: 'AON' },
        { StockName: 'AON', Code: 'AON' },
        { StockName: 'Boston Scientific Corporation', Code: 'BSX' },
        { StockName: 'BSX', Code: 'BSX' },
        { StockName: 'Equinix Inc.', Code: 'EQIX' },
        { StockName: 'EQIX', Code: 'EQIX' },
        { StockName: 'Micron Technology Inc.', Code: 'MU' },
        { StockName: 'MU', Code: 'MU' },
        { StockName: 'Activision Blizzard Inc.', Code: 'ATVI' },
        { StockName: 'ATVI', Code: 'ATVI' },
        { StockName: 'Dollar General Corporation', Code: 'DG' },
        { StockName: 'DG', Code: 'DG' },
        { StockName: 'General Motors Company', Code: 'GM' },
        { StockName: 'GM', Code: 'GM' },
        { StockName: 'Estee Lauder Companies Inc. Class A', Code: 'EL' },
        { StockName: 'EL', Code: 'EL' },
        { StockName: 'Pioneer Natural Resources Company', Code: 'PXD' },
        { StockName: 'PXD', Code: 'PXD' },
        { StockName: 'Schlumberger NV', Code: 'SLB' },
        { StockName: 'SLB', Code: 'SLB' },
        { StockName: 'Eaton Corp. Plc', Code: 'ETN' },
        { StockName: 'ETN', Code: 'ETN' },
        { StockName: 'Illinois Tool Works Inc.', Code: 'ITW' },
        { StockName: 'ITW', Code: 'ITW' },
        { StockName: 'Lam Research Corporation', Code: 'LRCX' },
        { StockName: 'LRCX', Code: 'LRCX' },
        { StockName: 'Norfolk Southern Corporation', Code: 'NSC' },
        { StockName: 'NSC', Code: 'NSC' },
        { StockName: 'Air Products and Chemicals Inc.', Code: 'APD' },
        { StockName: 'APD', Code: 'APD' },
        { StockName: 'Intercontinental Exchange Inc.', Code: 'ICE' },
        { StockName: 'ICE', Code: 'ICE' },
        { StockName: 'Edwards Lifesciences Corporation', Code: 'EW' },
        { StockName: 'EW', Code: 'EW' },
        { StockName: 'Sempra Energy', Code: 'SRE' },
        { StockName: 'SRE', Code: 'SRE' },
        { StockName: 'General Dynamics Corporation', Code: 'GD' },
        { StockName: 'GD', Code: 'GD' },
        { StockName: 'American Electric Power Company Inc.', Code: 'AEP' },
        { StockName: 'AEP', Code: 'AEP' },
        { StockName: 'Ford Motor Company', Code: 'F' },
        { StockName: 'F', Code: 'F' },
        { StockName: 'McKesson Corporation', Code: 'MCK' },
        { StockName: 'MCK', Code: 'MCK' },
        { StockName: 'Sherwin-Williams Company', Code: 'SHW' },
        { StockName: 'SHW', Code: 'SHW' },
        { StockName: 'Fidelity National Information Services Inc.', Code: 'FIS' },
        { StockName: 'FIS', Code: 'FIS' },
        { StockName: 'General Mills Inc.', Code: 'GIS' },
        { StockName: 'GIS', Code: 'GIS' },
        { StockName: 'Archer-Daniels-Midland Company', Code: 'ADM' },
        { StockName: 'ADM', Code: 'ADM' },
        { StockName: 'Marathon Petroleum Corporation', Code: 'MPC' },
        { StockName: 'MPC', Code: 'MPC' },
        { StockName: 'Public Storage', Code: 'PSA' },
        { StockName: 'PSA', Code: 'PSA' },
        { StockName: 'Synopsys Inc.', Code: 'SNPS' },
        { StockName: 'SNPS', Code: 'SNPS' },
        { StockName: 'Occidental Petroleum Corporation', Code: 'OXY' },
        { StockName: 'OXY', Code: 'OXY' },
        { StockName: 'Centene Corporation', Code: 'CNC' },
        { StockName: 'CNC', Code: 'CNC' },
        { StockName: 'Emerson Electric Co.', Code: 'EMR' },
        { StockName: 'EMR', Code: 'EMR' },
        { StockName: 'Cadence Design Systems Inc.', Code: 'CDNS' },
        { StockName: 'CDNS', Code: 'CDNS' },
        { StockName: 'KLA Corporation', Code: 'KLAC' },
        { StockName: 'KLAC', Code: 'KLAC' },
        {
            StockName: 'O\'Reilly Automotive Inc.', Code: 'ORLY'
        },
        { StockName: 'ORLY', Code: 'ORLY' },
        { StockName: 'Chipotle Mexican Grill Inc.', Code: 'CMG' },
        { StockName: 'CMG', Code: 'CMG' },
        { StockName: 'L3Harris Technologies Inc', Code: 'LHX' },
        { StockName: 'LHX', Code: 'LHX' },
        { StockName: 'Corteva Inc', Code: 'CTVA' },
        { StockName: 'CTVA', Code: 'CTVA' },
        { StockName: 'MetLife Inc.', Code: 'MET' },
        { StockName: 'MET', Code: 'MET' },
        { StockName: 'Valero Energy Corporation', Code: 'VLO' },
        { StockName: 'VLO', Code: 'VLO' },
        { StockName: 'Moderna Inc.', Code: 'MRNA' },
        { StockName: 'MRNA', Code: 'MRNA' },
        { StockName: 'HCA Healthcare Inc', Code: 'HCA' },
        { StockName: 'HCA', Code: 'HCA' },
        { StockName: 'Exelon Corporation', Code: 'EXC' },
        { StockName: 'EXC', Code: 'EXC' },
        { StockName: 'Devon Energy Corporation', Code: 'DVN' },
        { StockName: 'DVN', Code: 'DVN' },
        { StockName: 'Amphenol Corporation Class A', Code: 'APH' },
        { StockName: 'APH', Code: 'APH' },
        { StockName: 'NXP Semiconductors NV', Code: 'NXPI' },
        { StockName: 'NXPI', Code: 'NXPI' },
        { StockName: 'Autodesk Inc.', Code: 'ADSK' },
        { StockName: 'ADSK', Code: 'ADSK' },
        { StockName: 'Kimberly-Clark Corporation', Code: 'KMB' },
        { StockName: 'KMB', Code: 'KMB' },
        { StockName: 'AutoZone Inc.', Code: 'AZO' },
        { StockName: 'AZO', Code: 'AZO' },
        { StockName: 'Freeport-McMoRan Inc.', Code: 'FCX' },
        { StockName: 'FCX', Code: 'FCX' },
        {
            StockName: 'Moody\'s Corporation', Code: 'MCO'
        },
        { StockName: 'MCO', Code: 'MCO' },
        { StockName: 'Roper Technologies Inc.', Code: 'ROP' },
        { StockName: 'ROP', Code: 'ROP' },
        { StockName: 'Phillips 66', Code: 'PSX' },
        { StockName: 'PSX', Code: 'PSX' },
        { StockName: 'Sysco Corporation', Code: 'SYY' },
        { StockName: 'SYY', Code: 'SYY' },
        { StockName: 'Xcel Energy Inc.', Code: 'XEL' },
        { StockName: 'XEL', Code: 'XEL' },
        { StockName: 'American International Group Inc.', Code: 'AIG' },
        { StockName: 'AIG', Code: 'AIG' },
        { StockName: 'Motorola Solutions Inc.', Code: 'MSI' },
        { StockName: 'MSI', Code: 'MSI' },
        { StockName: 'Realty Income Corporation', Code: 'O' },
        { StockName: 'O', Code: 'O' },
        { StockName: 'Enphase Energy Inc.', Code: 'ENPH' },
        { StockName: 'ENPH', Code: 'ENPH' },
        { StockName: 'Marriott International Inc. Class A', Code: 'MAR' },
        { StockName: 'MAR', Code: 'MAR' },
        { StockName: 'Williams Companies Inc.', Code: 'WMB' },
        { StockName: 'WMB', Code: 'WMB' },
        { StockName: 'Constellation Brands Inc. Class A', Code: 'STZ' },
        { StockName: 'STZ', Code: 'STZ' },
        { StockName: 'Travelers Companies Inc.', Code: 'TRV' },
        { StockName: 'TRV', Code: 'TRV' },
        { StockName: 'Paychex Inc.', Code: 'PAYX' },
        { StockName: 'PAYX', Code: 'PAYX' },
        { StockName: 'Agilent Technologies Inc.', Code: 'A' },
        { StockName: 'A', Code: 'A' },
        { StockName: 'TE Connectivity Ltd.', Code: 'TEL' },
        { StockName: 'TEL', Code: 'TEL' },
        { StockName: 'Charter Communications Inc. Class A', Code: 'CHTR' },
        { StockName: 'CHTR', Code: 'CHTR' },
        { StockName: 'Ecolab Inc.', Code: 'ECL' },
        { StockName: 'ECL', Code: 'ECL' },
        { StockName: 'FedEx Corporation', Code: 'FDX' },
        { StockName: 'FDX', Code: 'FDX' },
        { StockName: 'Capital One Financial Corp', Code: 'COF' },
        { StockName: 'COF', Code: 'COF' },
        { StockName: 'Arthur J. Gallagher & Co.', Code: 'AJG' },
        { StockName: 'AJG', Code: 'AJG' },
        { StockName: 'IQVIA Holdings Inc', Code: 'IQV' },
        { StockName: 'IQV', Code: 'IQV' },
        { StockName: 'Johnson Controls International plc', Code: 'JCI' },
        { StockName: 'JCI', Code: 'JCI' },
        { StockName: 'Microchip Technology Incorporated', Code: 'MCHP' },
        { StockName: 'MCHP', Code: 'MCHP' },
        { StockName: 'Allstate Corporation', Code: 'ALL' },
        { StockName: 'ALL', Code: 'ALL' },
        { StockName: 'MSCI Inc. Class A', Code: 'MSCI' },
        { StockName: 'MSCI', Code: 'MSCI' },
        { StockName: 'Kinder Morgan Inc Class P', Code: 'KMI' },
        { StockName: 'KMI', Code: 'KMI' },
        { StockName: 'Trane Technologies plc', Code: 'TT' },
        { StockName: 'TT', Code: 'TT' },
        { StockName: 'Prudential Financial Inc.', Code: 'PRU' },
        { StockName: 'PRU', Code: 'PRU' },
        { StockName: 'Consolidated Edison Inc.', Code: 'ED' },
        { StockName: 'ED', Code: 'ED' },
        { StockName: 'Aflac Incorporated', Code: 'AFL' },
        { StockName: 'AFL', Code: 'AFL' },
        { StockName: 'Newmont Corporation', Code: 'NEM' },
        { StockName: 'NEM', Code: 'NEM' },
        { StockName: 'Cintas Corporation', Code: 'CTAS' },
        { StockName: 'CTAS', Code: 'CTAS' },
        { StockName: 'Monster Beverage Corporation', Code: 'MNST' },
        { StockName: 'MNST', Code: 'MNST' },
        { StockName: 'Hershey Company', Code: 'HSY' },
        { StockName: 'HSY', Code: 'HSY' },
        { StockName: 'Hilton Worldwide Holdings Inc', Code: 'HLT' },
        { StockName: 'HLT', Code: 'HLT' },
        { StockName: 'M&T Bank Corporation', Code: 'MTB' },
        { StockName: 'MTB', Code: 'MTB' },
        { StockName: 'Global Payments Inc.', Code: 'GPN' },
        { StockName: 'GPN', Code: 'GPN' },
        { StockName: 'Dow Inc.', Code: 'DOW' },
        { StockName: 'DOW', Code: 'DOW' },
        { StockName: 'SBA Communications Corp. Class A', Code: 'SBAC' },
        { StockName: 'SBAC', Code: 'SBAC' },
        { StockName: 'Public Service Enterprise Group Inc', Code: 'PEG' },
        { StockName: 'PEG', Code: 'PEG' },
        { StockName: 'Parker-Hannifin Corporation', Code: 'PH' },
        { StockName: 'PH', Code: 'PH' },
        { StockName: 'Fortinet Inc.', Code: 'FTNT' },
        { StockName: 'FTNT', Code: 'FTNT' },
        { StockName: 'Yum! Brands Inc.', Code: 'YUM' },
        { StockName: 'YUM', Code: 'YUM' },
        { StockName: 'DexCom Inc.', Code: 'DXCM' },
        { StockName: 'DXCM', Code: 'DXCM' },
        { StockName: 'Welltower Inc', Code: 'WELL' },
        { StockName: 'WELL', Code: 'WELL' },
        { StockName: 'Hess Corporation', Code: 'HES' },
        { StockName: 'HES', Code: 'HES' },
        { StockName: 'Keurig Dr Pepper Inc.', Code: 'KDP' },
        { StockName: 'KDP', Code: 'KDP' },
        { StockName: 'Albemarle Corporation', Code: 'ALB' },
        { StockName: 'ALB', Code: 'ALB' },
        { StockName: 'WEC Energy Group Inc', Code: 'WEC' },
        { StockName: 'WEC', Code: 'WEC' },
        { StockName: 'Cognizant Technology Solutions Corporation Class A', Code: 'CTSH' },
        { StockName: 'CTSH', Code: 'CTSH' },
        { StockName: 'ResMed Inc.', Code: 'RMD' },
        { StockName: 'RMD', Code: 'RMD' },
        { StockName: 'Electronic Arts Inc.', Code: 'EA' },
        { StockName: 'EA', Code: 'EA' },
        { StockName: 'Digital Realty Trust Inc.', Code: 'DLR' },
        { StockName: 'DLR', Code: 'DLR' },
        { StockName: 'Carrier Global Corp.', Code: 'CARR' },
        { StockName: 'CARR', Code: 'CARR' },
        { StockName: 'Ross Stores Inc.', Code: 'ROST' },
        { StockName: 'ROST', Code: 'ROST' },
        { StockName: 'Eversource Energy', Code: 'ES' },
        { StockName: 'ES', Code: 'ES' },
        { StockName: 'VICI Properties Inc', Code: 'VICI' },
        { StockName: 'VICI', Code: 'VICI' },
        { StockName: 'Bank of New York Mellon Corp', Code: 'BK' },
        { StockName: 'BK', Code: 'BK' },
        { StockName: 'Illumina Inc.', Code: 'ILMN' },
        { StockName: 'ILMN', Code: 'ILMN' },
        { StockName: 'Simon Property Group Inc.', Code: 'SPG' },
        { StockName: 'SPG', Code: 'SPG' },
        { StockName: 'Kroger Co.', Code: 'KR' },
        { StockName: 'KR', Code: 'KR' },
        { StockName: 'Republic Services Inc.', Code: 'RSG' },
        { StockName: 'RSG', Code: 'RSG' },
        { StockName: 'Cummins Inc.', Code: 'CMI' },
        { StockName: 'CMI', Code: 'CMI' },
        { StockName: 'Dollar Tree Inc.', Code: 'DLTR' },
        { StockName: 'DLTR', Code: 'DLTR' },
        { StockName: 'Biogen Inc.', Code: 'BIIB' },
        { StockName: 'BIIB', Code: 'BIIB' },
        { StockName: 'PACCAR Inc', Code: 'PCAR' },
        { StockName: 'PCAR', Code: 'PCAR' },
        { StockName: 'Nucor Corporation', Code: 'NUE' },
        { StockName: 'NUE', Code: 'NUE' },
        { StockName: 'Ameriprise Financial Inc.', Code: 'AMP' },
        { StockName: 'AMP', Code: 'AMP' },
        { StockName: 'TransDigm Group Incorporated', Code: 'TDG' },
        { StockName: 'TDG', Code: 'TDG' },
        { StockName: 'Keysight Technologies Inc', Code: 'KEYS' },
        { StockName: 'KEYS', Code: 'KEYS' },
        { StockName: 'ON Semiconductor Corporation', Code: 'ON' },
        { StockName: 'ON', Code: 'ON' },
        { StockName: 'Twitter Inc.', Code: 'TWTR' },
        { StockName: 'TWTR', Code: 'TWTR' },
        { StockName: 'Baxter International Inc.', Code: 'BAX' },
        { StockName: 'BAX', Code: 'BAX' },
        { StockName: 'CoStar Group Inc.', Code: 'CSGP' },
        { StockName: 'CSGP', Code: 'CSGP' },
        { StockName: 'Arista Networks Inc.', Code: 'ANET' },
        { StockName: 'ANET', Code: 'ANET' },
        { StockName: 'Otis Worldwide Corporation', Code: 'OTIS' },
        { StockName: 'OTIS', Code: 'OTIS' },
        { StockName: 'Constellation Energy Corporation', Code: 'CEG' },
        { StockName: 'CEG', Code: 'CEG' },
        { StockName: 'IDEXX Laboratories Inc.', Code: 'IDXX' },
        { StockName: 'IDXX', Code: 'IDXX' },
        { StockName: 'Verisk Analytics Inc', Code: 'VRSK' },
        { StockName: 'VRSK', Code: 'VRSK' },
        { StockName: 'Kraft Heinz Company', Code: 'KHC' },
        { StockName: 'KHC', Code: 'KHC' },
        { StockName: 'Fastenal Company', Code: 'FAST' },
        { StockName: 'FAST', Code: 'FAST' },
        { StockName: 'AMETEK Inc.', Code: 'AME' },
        { StockName: 'AME', Code: 'AME' },
        { StockName: 'Warner Bros. Discovery Inc. Series A', Code: 'WBD' },
        { StockName: 'WBD', Code: 'WBD' },
        { StockName: 'PPG Industries Inc.', Code: 'PPG' },
        { StockName: 'PPG', Code: 'PPG' },
        { StockName: 'DuPont de Nemours Inc.', Code: 'DD' },
        { StockName: 'DD', Code: 'DD' },
        { StockName: 'AvalonBay Communities Inc.', Code: 'AVB' },
        { StockName: 'AVB', Code: 'AVB' },
        { StockName: 'Discover Financial Services', Code: 'DFS' },
        { StockName: 'DFS', Code: 'DFS' },
        { StockName: 'Rockwell Automation Inc.', Code: 'ROK' },
        { StockName: 'ROK', Code: 'ROK' },
        { StockName: 'American Water Works Company Inc.', Code: 'AWK' },
        { StockName: 'AWK', Code: 'AWK' },
        { StockName: 'Mettler-Toledo International Inc.', Code: 'MTD' },
        { StockName: 'MTD', Code: 'MTD' },
        { StockName: 'ONEOK Inc.', Code: 'OKE' },
        { StockName: 'OKE', Code: 'OKE' },
        { StockName: 'Edison International', Code: 'EIX' },
        { StockName: 'EIX', Code: 'EIX' },
        { StockName: 'International Flavors & Fragrances Inc.', Code: 'IFF' },
        { StockName: 'IFF', Code: 'IFF' },
        { StockName: 'First Republic Bank', Code: 'FRC' },
        { StockName: 'FRC', Code: 'FRC' },
        { StockName: 'T. Rowe Price Group', Code: 'TROW' },
        { StockName: 'TROW', Code: 'TROW' },
        { StockName: 'DTE Energy Company', Code: 'DTE' },
        { StockName: 'DTE', Code: 'DTE' },
        { StockName: 'Halliburton Company', Code: 'HAL' },
        { StockName: 'HAL', Code: 'HAL' },
        { StockName: 'State Street Corporation', Code: 'STT' },
        { StockName: 'STT', Code: 'STT' },
        { StockName: 'Walgreens Boots Alliance Inc.', Code: 'WBA' },
        { StockName: 'WBA', Code: 'WBA' },
        { StockName: 'CBRE Group Inc. Class A', Code: 'CBRE' },
        { StockName: 'CBRE', Code: 'CBRE' },
        { StockName: 'HP Inc.', Code: 'HPQ' },
        { StockName: 'HPQ', Code: 'HPQ' },
        { StockName: 'Corning Inc', Code: 'GLW' },
        { StockName: 'GLW', Code: 'GLW' },
        { StockName: 'Aptiv PLC', Code: 'APTV' },
        { StockName: 'APTV', Code: 'APTV' },
        { StockName: 'Baker Hughes Company Class A', Code: 'BKR' },
        { StockName: 'BKR', Code: 'BKR' },
        { StockName: 'Equity Residential', Code: 'EQR' },
        { StockName: 'EQR', Code: 'EQR' },
        { StockName: 'Extra Space Storage Inc.', Code: 'EXR' },
        { StockName: 'EXR', Code: 'EXR' },
        { StockName: 'Entergy Corporation', Code: 'ETR' },
        { StockName: 'ETR', Code: 'ETR' },
        { StockName: 'Ameren Corporation', Code: 'AEE' },
        { StockName: 'AEE', Code: 'AEE' },
        { StockName: 'W.W. Grainger Inc.', Code: 'GWW' },
        { StockName: 'GWW', Code: 'GWW' },
        { StockName: 'Old Dominion Freight Line Inc.', Code: 'ODFL' },
        { StockName: 'ODFL', Code: 'ODFL' },
        { StockName: 'Willis Towers Watson Public Limited Company', Code: 'WTW' },
        { StockName: 'WTW', Code: 'WTW' },
        { StockName: 'Coterra Energy Inc.', Code: 'CTRA' },
        { StockName: 'CTRA', Code: 'CTRA' },
        { StockName: 'Fifth Third Bancorp', Code: 'FITB' },
        { StockName: 'FITB', Code: 'FITB' },
        { StockName: 'Diamondback Energy Inc.', Code: 'FANG' },
        { StockName: 'FANG', Code: 'FANG' },
        { StockName: 'D.R. Horton Inc.', Code: 'DHI' },
        { StockName: 'DHI', Code: 'DHI' },
        { StockName: 'Zimmer Biomet Holdings Inc.', Code: 'ZBH' },
        { StockName: 'ZBH', Code: 'ZBH' },
        { StockName: 'Copart Inc.', Code: 'CPRT' },
        { StockName: 'CPRT', Code: 'CPRT' },
        { StockName: 'Gartner Inc.', Code: 'IT' },
        { StockName: 'IT', Code: 'IT' },
        { StockName: 'FirstEnergy Corp.', Code: 'FE' },
        { StockName: 'FE', Code: 'FE' },
        { StockName: 'Genuine Parts Company', Code: 'GPC' },
        { StockName: 'GPC', Code: 'GPC' },
        { StockName: 'CDW Corp.', Code: 'CDW' },
        { StockName: 'CDW', Code: 'CDW' },
        { StockName: 'Weyerhaeuser Company', Code: 'WY' },
        { StockName: 'WY', Code: 'WY' },
        { StockName: 'AmerisourceBergen Corporation', Code: 'ABC' },
        { StockName: 'ABC', Code: 'ABC' },
        { StockName: 'Fortive Corp.', Code: 'FTV' },
        { StockName: 'FTV', Code: 'FTV' },
        { StockName: 'eBay Inc.', Code: 'EBAY' },
        { StockName: 'EBAY', Code: 'EBAY' },
        { StockName: 'PPL Corporation', Code: 'PPL' },
        { StockName: 'PPL', Code: 'PPL' },
        { StockName: 'EPAM Systems Inc.', Code: 'EPAM' },
        { StockName: 'EPAM', Code: 'EPAM' },
        { StockName: 'Alexandria Real Estate Equities Inc.', Code: 'ARE' },
        { StockName: 'ARE', Code: 'ARE' },
        { StockName: 'Ulta Beauty Inc.', Code: 'ULTA' },
        { StockName: 'ULTA', Code: 'ULTA' },
        { StockName: 'Tractor Supply Company', Code: 'TSCO' },
        { StockName: 'TSCO', Code: 'TSCO' },
        { StockName: 'Vulcan Materials Company', Code: 'VMC' },
        { StockName: 'VMC', Code: 'VMC' },
        { StockName: 'Equifax Inc.', Code: 'EFX' },
        { StockName: 'EFX', Code: 'EFX' },
        { StockName: 'Tyson Foods Inc. Class A', Code: 'TSN' },
        { StockName: 'TSN', Code: 'TSN' },
        { StockName: 'Raymond James Financial Inc.', Code: 'RJF' },
        { StockName: 'RJF', Code: 'RJF' },
        { StockName: 'Invitation Homes Inc.', Code: 'INVH' },
        { StockName: 'INVH', Code: 'INVH' },
        { StockName: 'Martin Marietta Materials Inc.', Code: 'MLM' },
        { StockName: 'MLM', Code: 'MLM' },
        { StockName: 'CF Industries Holdings Inc.', Code: 'CF' },
        { StockName: 'CF', Code: 'CF' },
        { StockName: 'Hartford Financial Services Group Inc.', Code: 'HIG' },
        { StockName: 'HIG', Code: 'HIG' },
        { StockName: 'Lennar Corporation Class A', Code: 'LEN' },
        { StockName: 'LEN', Code: 'LEN' },
        { StockName: 'Regions Financial Corporation', Code: 'RF' },
        { StockName: 'RF', Code: 'RF' },
        { StockName: 'ANSYS Inc.', Code: 'ANSS' },
        { StockName: 'ANSS', Code: 'ANSS' },
        { StockName: 'SVB Financial Group', Code: 'SIVB' },
        { StockName: 'SIVB', Code: 'SIVB' },
        { StockName: 'Nasdaq Inc.', Code: 'NDAQ' },
        { StockName: 'NDAQ', Code: 'NDAQ' },
        { StockName: 'CenterPoint Energy Inc.', Code: 'CNP' },
        { StockName: 'CNP', Code: 'CNP' },
        { StockName: 'Duke Realty Corporation', Code: 'DRE' },
        { StockName: 'DRE', Code: 'DRE' },
        { StockName: 'Southwest Airlines Co.', Code: 'LUV' },
        { StockName: 'LUV', Code: 'LUV' },
        { StockName: 'Laboratory Corporation of America Holdings', Code: 'LH' },
        { StockName: 'LH', Code: 'LH' },
        { StockName: 'Huntington Bancshares Incorporated', Code: 'HBAN' },
        { StockName: 'HBAN', Code: 'HBAN' },
        { StockName: 'Quanta Services Inc.', Code: 'PWR' },
        { StockName: 'PWR', Code: 'PWR' },
        { StockName: 'Molina Healthcare Inc.', Code: 'MOH' },
        { StockName: 'MOH', Code: 'MOH' },
        { StockName: 'United Rentals Inc.', Code: 'URI' },
        { StockName: 'URI', Code: 'URI' },
        { StockName: 'LyondellBasell Industries NV', Code: 'LYB' },
        { StockName: 'LYB', Code: 'LYB' },
        { StockName: 'Delta Air Lines Inc.', Code: 'DAL' },
        { StockName: 'DAL', Code: 'DAL' },
        { StockName: 'CMS Energy Corporation', Code: 'CMS' },
        { StockName: 'CMS', Code: 'CMS' },
        { StockName: 'McCormick & Company Incorporated', Code: 'MKC' },
        { StockName: 'MKC', Code: 'MKC' },
        { StockName: 'Cardinal Health Inc.', Code: 'CAH' },
        { StockName: 'CAH', Code: 'CAH' },
        { StockName: 'West Pharmaceutical Services Inc.', Code: 'WST' },
        { StockName: 'WST', Code: 'WST' },
        { StockName: 'Kellogg Company', Code: 'K' },
        { StockName: 'K', Code: 'K' },
        { StockName: 'Northern Trust Corporation', Code: 'NTRS' },
        { StockName: 'NTRS', Code: 'NTRS' },
        { StockName: 'Church & Dwight Co. Inc.', Code: 'CHD' },
        { StockName: 'CHD', Code: 'CHD' },
        { StockName: 'Mosaic Company', Code: 'MOS' },
        { StockName: 'MOS', Code: 'MOS' },
        { StockName: 'Mid-America Apartment Communities Inc.', Code: 'MAA' },
        { StockName: 'MAA', Code: 'MAA' },
        { StockName: 'Broadridge Financial Solutions Inc.', Code: 'BR' },
        { StockName: 'BR', Code: 'BR' },
        { StockName: 'Take-Two Interactive Software Inc.', Code: 'TTWO' },
        { StockName: 'TTWO', Code: 'TTWO' },
        { StockName: 'Ingersoll Rand Inc.', Code: 'IR' },
        { StockName: 'IR', Code: 'IR' },
        { StockName: 'Principal Financial Group Inc.', Code: 'PFG' },
        { StockName: 'PFG', Code: 'PFG' },
        { StockName: 'Ventas Inc.', Code: 'VTR' },
        { StockName: 'VTR', Code: 'VTR' },
        { StockName: 'STERIS Plc', Code: 'STE' },
        { StockName: 'STE', Code: 'STE' },
        { StockName: 'Citizens Financial Group Inc.', Code: 'CFG' },
        { StockName: 'CFG', Code: 'CFG' },
        { StockName: 'Clorox Company', Code: 'CLX' },
        { StockName: 'CLX', Code: 'CLX' },
        { StockName: 'Dover Corporation', Code: 'DOV' },
        { StockName: 'DOV', Code: 'DOV' },
        { StockName: 'Monolithic Power Systems Inc.', Code: 'MPWR' },
        { StockName: 'MPWR', Code: 'MPWR' },
        { StockName: 'Amcor PLC', Code: 'AMCR' },
        { StockName: 'AMCR', Code: 'AMCR' },
        { StockName: 'Waters Corporation', Code: 'WAT' },
        { StockName: 'WAT', Code: 'WAT' },
        { StockName: 'Teledyne Technologies Incorporated', Code: 'TDY' },
        { StockName: 'TDY', Code: 'TDY' },
        { StockName: 'Marathon Oil Corporation', Code: 'MRO' },
        { StockName: 'MRO', Code: 'MRO' },
        { StockName: 'Conagra Brands Inc.', Code: 'CAG' },
        { StockName: 'CAG', Code: 'CAG' },
        { StockName: 'AES Corporation', Code: 'AES' },
        { StockName: 'AES', Code: 'AES' },
        { StockName: 'VeriSign Inc.', Code: 'VRSN' },
        { StockName: 'VRSN', Code: 'VRSN' },
        { StockName: 'Xylem Inc.', Code: 'XYL' },
        { StockName: 'XYL', Code: 'XYL' },
        { StockName: 'Hewlett Packard Enterprise Co.', Code: 'HPE' },
        { StockName: 'HPE', Code: 'HPE' },
        { StockName: 'Essex Property Trust Inc.', Code: 'ESS' },
        { StockName: 'ESS', Code: 'ESS' },
        { StockName: 'Align Technology Inc.', Code: 'ALGN' },
        { StockName: 'ALGN', Code: 'ALGN' },
        { StockName: 'Hologic Inc.', Code: 'HOLX' },
        { StockName: 'HOLX', Code: 'HOLX' },
        { StockName: 'Atmos Energy Corporation', Code: 'ATO' },
        { StockName: 'ATO', Code: 'ATO' },
        { StockName: 'Skyworks Solutions Inc.', Code: 'SWKS' },
        { StockName: 'SWKS', Code: 'SWKS' },
        { StockName: 'Paycom Software Inc.', Code: 'PAYC' },
        { StockName: 'PAYC', Code: 'PAYC' },
        { StockName: 'Ball Corporation', Code: 'BALL' },
        { StockName: 'BALL', Code: 'BALL' },
        { StockName: 'PerkinElmer Inc.', Code: 'PKI' },
        { StockName: 'PKI', Code: 'PKI' },
        { StockName: 'Darden Restaurants Inc.', Code: 'DRI' },
        { StockName: 'DRI', Code: 'DRI' },
        { StockName: 'Westinghouse Air Brake Technologies Corporation', Code: 'WAB' },
        { StockName: 'WAB', Code: 'WAB' },
        { StockName: 'KeyCorp', Code: 'KEY' },
        { StockName: 'KEY', Code: 'KEY' },
        { StockName: 'J.M. Smucker Company', Code: 'SJM' },
        { StockName: 'SJM', Code: 'SJM' },
        { StockName: 'IDEX Corporation', Code: 'IEX' },
        { StockName: 'IEX', Code: 'IEX' },
        { StockName: 'Jacobs Solutions Inc.', Code: 'J' },
        { StockName: 'J', Code: 'J' },
        { StockName: 'SolarEdge Technologies Inc.', Code: 'SEDG' },
        { StockName: 'SEDG', Code: 'SEDG' },
        { StockName: 'Evergy Inc.', Code: 'EVRG' },
        { StockName: 'EVRG', Code: 'EVRG' },
        { StockName: 'Alliant Energy Corp', Code: 'LNT' },
        { StockName: 'LNT', Code: 'LNT' },
        { StockName: 'FactSet Research Systems Inc.', Code: 'FDS' },
        { StockName: 'FDS', Code: 'FDS' },
        { StockName: 'Cincinnati Financial Corporation', Code: 'CINF' },
        { StockName: 'CINF', Code: 'CINF' },
        { StockName: 'Quest Diagnostics Incorporated', Code: 'DGX' },
        { StockName: 'DGX', Code: 'DGX' },
        { StockName: 'Zebra Technologies Corporation Class A', Code: 'ZBRA' },
        { StockName: 'ZBRA', Code: 'ZBRA' },
        { StockName: 'Expeditors International of Washington Inc.', Code: 'EXPD' },
        { StockName: 'EXPD', Code: 'EXPD' },
        { StockName: 'Synchrony Financial', Code: 'SYF' },
        { StockName: 'SYF', Code: 'SYF' },
        { StockName: 'NetApp Inc.', Code: 'NTAP' },
        { StockName: 'NTAP', Code: 'NTAP' },
        { StockName: 'FLEETCOR Technologies Inc.', Code: 'FLT' },
        { StockName: 'FLT', Code: 'FLT' },
        { StockName: 'Trimble Inc.', Code: 'TRMB' },
        { StockName: 'TRMB', Code: 'TRMB' },
        { StockName: 'Catalent Inc', Code: 'CTLT' },
        { StockName: 'CTLT', Code: 'CTLT' },
        { StockName: 'Avery Dennison Corporation', Code: 'AVY' },
        { StockName: 'AVY', Code: 'AVY' },
        { StockName: 'Tyler Technologies Inc.', Code: 'TYL' },
        { StockName: 'TYL', Code: 'TYL' },
        { StockName: 'Best Buy Co. Inc.', Code: 'BBY' },
        { StockName: 'BBY', Code: 'BBY' },
        { StockName: 'Iron Mountain Inc.', Code: 'IRM' },
        { StockName: 'IRM', Code: 'IRM' },
        { StockName: 'Expedia Group Inc.', Code: 'EXPE' },
        { StockName: 'EXPE', Code: 'EXPE' },
        { StockName: 'Brown & Brown Inc.', Code: 'BRO' },
        { StockName: 'BRO', Code: 'BRO' },
        { StockName: 'Jack Henry & Associates Inc.', Code: 'JKHY' },
        { StockName: 'JKHY', Code: 'JKHY' },
        { StockName: 'Match Group Inc.', Code: 'MTCH' },
        { StockName: 'MTCH', Code: 'MTCH' },
        { StockName: 'J.B. Hunt Transport Services Inc.', Code: 'JBHT' },
        { StockName: 'JBHT', Code: 'JBHT' },
        { StockName: 'Hormel Foods Corporation', Code: 'HRL' },
        { StockName: 'HRL', Code: 'HRL' },
        { StockName: 'FMC Corporation', Code: 'FMC' },
        { StockName: 'FMC', Code: 'FMC' },
        { StockName: 'W. R. Berkley Corporation', Code: 'WRB' },
        { StockName: 'WRB', Code: 'WRB' },
        { StockName: 'Cooper Companies Inc.', Code: 'COO' },
        { StockName: 'COO', Code: 'COO' },
        { StockName: 'Omnicom Group Inc', Code: 'OMC' },
        { StockName: 'OMC', Code: 'OMC' },
        { StockName: 'Akamai Technologies Inc.', Code: 'AKAM' },
        { StockName: 'AKAM', Code: 'AKAM' },
        { StockName: 'Healthpeak Properties Inc.', Code: 'PEAK' },
        { StockName: 'PEAK', Code: 'PEAK' },
        { StockName: 'Camden Property Trust', Code: 'CPT' },
        { StockName: 'CPT', Code: 'CPT' },
        { StockName: 'Textron Inc.', Code: 'TXT' },
        { StockName: 'TXT', Code: 'TXT' },
        { StockName: 'Teradyne Inc.', Code: 'TER' },
        { StockName: 'TER', Code: 'TER' },
        { StockName: 'CarMax Inc.', Code: 'KMX' },
        { StockName: 'KMX', Code: 'KMX' },
        { StockName: 'Garmin Ltd.', Code: 'GRMN' },
        { StockName: 'GRMN', Code: 'GRMN' },
        { StockName: 'Citrix Systems Inc.', Code: 'CTXS' },
        { StockName: 'CTXS', Code: 'CTXS' },
        { StockName: 'Brown-Forman Corporation Class B', Code: 'BF.B' },
        { StockName: 'BF.B', Code: 'BF.B' },
        { StockName: 'Leidos Holdings Inc.', Code: 'LDOS' },
        { StockName: 'LDOS', Code: 'LDOS' },
        { StockName: 'Incyte Corporation', Code: 'INCY' },
        { StockName: 'INCY', Code: 'INCY' },
        { StockName: 'Pool Corporation', Code: 'POOL' },
        { StockName: 'POOL', Code: 'POOL' },
        { StockName: 'International Paper Company', Code: 'IP' },
        { StockName: 'IP', Code: 'IP' },
        { StockName: 'UDR Inc.', Code: 'UDR' },
        { StockName: 'UDR', Code: 'UDR' },
        { StockName: 'C.H. Robinson Worldwide Inc.', Code: 'CHRW' },
        { StockName: 'CHRW', Code: 'CHRW' },
        { StockName: 'Cboe Global Markets Inc', Code: 'CBOE' },
        { StockName: 'CBOE', Code: 'CBOE' },
        { StockName: 'Howmet Aerospace Inc.', Code: 'HWM' },
        { StockName: 'HWM', Code: 'HWM' },
        { StockName: 'LKQ Corporation', Code: 'LKQ' },
        { StockName: 'LKQ', Code: 'LKQ' },
        { StockName: 'NVR Inc.', Code: 'NVR' },
        { StockName: 'NVR', Code: 'NVR' },
        { StockName: 'Etsy Inc.', Code: 'ETSY' },
        { StockName: 'ETSY', Code: 'ETSY' },
        { StockName: 'NortonLifeLock Inc.', Code: 'NLOK' },
        { StockName: 'NLOK', Code: 'NLOK' },
        { StockName: 'Stanley Black & Decker Inc.', Code: 'SWK' },
        { StockName: 'SWK', Code: 'SWK' },
        { StockName: 'APA Corp.', Code: 'APA' },
        { StockName: 'APA', Code: 'APA' },
        { StockName: 'Kimco Realty Corporation', Code: 'KIM' },
        { StockName: 'KIM', Code: 'KIM' },
        { StockName: 'Seagate Technology Holdings PLC', Code: 'STX' },
        { StockName: 'STX', Code: 'STX' },
        {
            StockName: 'Domino\'s Pizza Inc.', Code: 'DPZ'
        },
        { StockName: 'DPZ', Code: 'DPZ' },
        { StockName: 'V.F. Corporation', Code: 'VFC' },
        { StockName: 'VFC', Code: 'VFC' },
        { StockName: 'Nordson Corporation', Code: 'NDSN' },
        { StockName: 'NDSN', Code: 'NDSN' },
        { StockName: 'Las Vegas Sands Corp.', Code: 'LVS' },
        { StockName: 'LVS', Code: 'LVS' },
        { StockName: 'NiSource Inc', Code: 'NI' },
        { StockName: 'NI', Code: 'NI' },
        { StockName: 'PTC Inc.', Code: 'PTC' },
        { StockName: 'PTC', Code: 'PTC' },
        { StockName: 'Host Hotels & Resorts Inc.', Code: 'HST' },
        { StockName: 'HST', Code: 'HST' },
        { StockName: 'Snap-on Incorporated', Code: 'SNA' },
        { StockName: 'SNA', Code: 'SNA' },
        { StockName: 'Lamb Weston Holdings Inc.', Code: 'LW' },
        { StockName: 'LW', Code: 'LW' },
        { StockName: 'Bio-Techne Corporation', Code: 'TECH' },
        { StockName: 'TECH', Code: 'TECH' },
        { StockName: 'ABIOMED Inc.', Code: 'ABMD' },
        { StockName: 'ABMD', Code: 'ABMD' },
        { StockName: 'Live Nation Entertainment Inc.', Code: 'LYV' },
        { StockName: 'LYV', Code: 'LYV' },
        { StockName: 'United Airlines Holdings Inc.', Code: 'UAL' },
        { StockName: 'UAL', Code: 'UAL' },
        { StockName: 'Boston Properties Inc.', Code: 'BXP' },
        { StockName: 'BXP', Code: 'BXP' },
        { StockName: 'Packaging Corporation of America', Code: 'PKG' },
        { StockName: 'PKG', Code: 'PKG' },
        { StockName: 'Viatris Inc.', Code: 'VTRS' },
        { StockName: 'VTRS', Code: 'VTRS' },
        { StockName: 'Generac Holdings Inc.', Code: 'GNRC' },
        { StockName: 'GNRC', Code: 'GNRC' },
        { StockName: 'Paramount Global Class B', Code: 'PARA' },
        { StockName: 'PARA', Code: 'PARA' },
        { StockName: 'Western Digital Corporation', Code: 'WDC' },
        { StockName: 'WDC', Code: 'WDC' },
        { StockName: 'Masco Corporation', Code: 'MAS' },
        { StockName: 'MAS', Code: 'MAS' },
        { StockName: 'Royal Caribbean Group', Code: 'RCL' },
        { StockName: 'RCL', Code: 'RCL' },
        { StockName: 'Interpublic Group of Companies Inc.', Code: 'IPG' },
        { StockName: 'IPG', Code: 'IPG' },
        { StockName: 'Fox Corporation Class A', Code: 'FOXA' },
        { StockName: 'FOXA', Code: 'FOXA' },
        { StockName: 'Advance Auto Parts Inc.', Code: 'AAP' },
        { StockName: 'AAP', Code: 'AAP' },
        { StockName: 'Everest Re Group Ltd.', Code: 'RE' },
        { StockName: 'RE', Code: 'RE' },
        { StockName: 'NRG Energy Inc.', Code: 'NRG' },
        { StockName: 'NRG', Code: 'NRG' },
        { StockName: 'Loews Corporation', Code: 'L' },
        { StockName: 'L', Code: 'L' },
        { StockName: 'Comerica Incorporated', Code: 'CMA' },
        { StockName: 'CMA', Code: 'CMA' },
        { StockName: 'MGM Resorts International', Code: 'MGM' },
        { StockName: 'MGM', Code: 'MGM' },
        { StockName: 'Signature Bank', Code: 'SBNY' },
        { StockName: 'SBNY', Code: 'SBNY' },
        { StockName: 'Campbell Soup Company', Code: 'CPB' },
        { StockName: 'CPB', Code: 'CPB' },
        { StockName: 'Nielsen Holdings Plc', Code: 'NLSN' },
        { StockName: 'NLSN', Code: 'NLSN' },
        { StockName: 'Teleflex Incorporated', Code: 'TFX' },
        { StockName: 'TFX', Code: 'TFX' },
        { StockName: 'Globe Life Inc.', Code: 'GL' },
        { StockName: 'GL', Code: 'GL' },
        { StockName: 'Henry Schein Inc.', Code: 'HSIC' },
        { StockName: 'HSIC', Code: 'HSIC' },
        { StockName: 'Carnival Corporation', Code: 'CCL' },
        { StockName: 'CCL', Code: 'CCL' },
        { StockName: 'Celanese Corporation', Code: 'CE' },
        { StockName: 'CE', Code: 'CE' },
        { StockName: 'Huntington Ingalls Industries Inc.', Code: 'HII' },
        { StockName: 'HII', Code: 'HII' },
        { StockName: 'Hasbro Inc.', Code: 'HAS' },
        { StockName: 'HAS', Code: 'HAS' },
        { StockName: 'Molson Coors Beverage Company Class B', Code: 'TAP' },
        { StockName: 'TAP', Code: 'TAP' },
        { StockName: 'PulteGroup Inc.', Code: 'PHM' },
        { StockName: 'PHM', Code: 'PHM' },
        { StockName: 'Charles River Laboratories International Inc.', Code: 'CRL' },
        { StockName: 'CRL', Code: 'CRL' },
        { StockName: 'Eastman Chemical Company', Code: 'EMN' },
        { StockName: 'EMN', Code: 'EMN' },
        { StockName: 'Bio-Rad Laboratories Inc. Class A', Code: 'BIO' },
        { StockName: 'BIO', Code: 'BIO' },
        { StockName: 'Qorvo Inc.', Code: 'QRVO' },
        { StockName: 'QRVO', Code: 'QRVO' },
        { StockName: 'F5 Inc.', Code: 'FFIV' },
        { StockName: 'FFIV', Code: 'FFIV' },
        { StockName: 'Bath & Body Works Inc.', Code: 'BBWI' },
        { StockName: 'BBWI', Code: 'BBWI' },
        { StockName: 'WestRock Company', Code: 'WRK' },
        { StockName: 'WRK', Code: 'WRK' },
        { StockName: 'MarketAxess Holdings Inc.', Code: 'MKTX' },
        { StockName: 'MKTX', Code: 'MKTX' },
        { StockName: 'Ceridian HCM Holding Inc.', Code: 'CDAY' },
        { StockName: 'CDAY', Code: 'CDAY' },
        { StockName: 'Juniper Networks Inc.', Code: 'JNPR' },
        { StockName: 'JNPR', Code: 'JNPR' },
        { StockName: 'Zions Bancorporation N.A.', Code: 'ZION' },
        { StockName: 'ZION', Code: 'ZION' },
        { StockName: 'BorgWarner Inc.', Code: 'BWA' },
        { StockName: 'BWA', Code: 'BWA' },
        { StockName: 'Regency Centers Corporation', Code: 'REG' },
        { StockName: 'REG', Code: 'REG' },
        { StockName: 'Pinnacle West Capital Corporation', Code: 'PNW' },
        { StockName: 'PNW', Code: 'PNW' },
        { StockName: 'American Airlines Group Inc.', Code: 'AAL' },
        { StockName: 'AAL', Code: 'AAL' },
        { StockName: 'Tapestry Inc.', Code: 'TPR' },
        { StockName: 'TPR', Code: 'TPR' },
        { StockName: 'Robert Half International Inc.', Code: 'RHI' },
        { StockName: 'RHI', Code: 'RHI' },
        { StockName: 'Allegion Public Limited Company', Code: 'ALLE' },
        { StockName: 'ALLE', Code: 'ALLE' },
        { StockName: 'Caesars Entertainment Inc', Code: 'CZR' },
        { StockName: 'CZR', Code: 'CZR' },
        { StockName: 'Assurant Inc.', Code: 'AIZ' },
        { StockName: 'AIZ', Code: 'AIZ' },
        { StockName: 'Whirlpool Corporation', Code: 'WHR' },
        { StockName: 'WHR', Code: 'WHR' },
        { StockName: 'Rollins Inc.', Code: 'ROL' },
        { StockName: 'ROL', Code: 'ROL' },
        { StockName: 'Lumen Technologies Inc.', Code: 'LUMN' },
        { StockName: 'LUMN', Code: 'LUMN' },
        { StockName: 'Lincoln National Corporation', Code: 'LNC' },
        { StockName: 'LNC', Code: 'LNC' },
        { StockName: 'Fortune Brands Home & Security Inc.', Code: 'FBHS' },
        { StockName: 'FBHS', Code: 'FBHS' },
        { StockName: 'Invesco Ltd.', Code: 'IVZ' },
        { StockName: 'IVZ', Code: 'IVZ' },
        { StockName: 'Sealed Air Corporation', Code: 'SEE' },
        { StockName: 'SEE', Code: 'SEE' },
        { StockName: 'Pentair plc', Code: 'PNR' },
        { StockName: 'PNR', Code: 'PNR' },
        { StockName: 'A. O. Smith Corporation', Code: 'AOS' },
        { StockName: 'AOS', Code: 'AOS' },
        { StockName: 'Organon & Co.', Code: 'OGN' },
        { StockName: 'OGN', Code: 'OGN' },
        { StockName: 'Franklin Resources Inc.', Code: 'BEN' },
        { StockName: 'BEN', Code: 'BEN' },
        { StockName: 'DENTSPLY SIRONA Inc.', Code: 'XRAY' },
        { StockName: 'XRAY', Code: 'XRAY' },
        { StockName: 'Wynn Resorts Limited', Code: 'WYNN' },
        { StockName: 'WYNN', Code: 'WYNN' },
        { StockName: 'Federal Realty Investment Trust', Code: 'FRT' },
        { StockName: 'FRT', Code: 'FRT' },
        { StockName: 'Universal Health Services Inc. Class B', Code: 'UHS' },
        { StockName: 'UHS', Code: 'UHS' },
        { StockName: 'News Corporation Class A', Code: 'NWSA' },
        { StockName: 'NWSA', Code: 'NWSA' },
        { StockName: 'DXC Technology Co.', Code: 'DXC' },
        { StockName: 'DXC', Code: 'DXC' },
        { StockName: 'Norwegian Cruise Line Holdings Ltd.', Code: 'NCLH' },
        { StockName: 'NCLH', Code: 'NCLH' },
        { StockName: 'Newell Brands Inc', Code: 'NWL' },
        { StockName: 'NWL', Code: 'NWL' },
        { StockName: 'Alaska Air Group Inc.', Code: 'ALK' },
        { StockName: 'ALK', Code: 'ALK' },
        { StockName: 'DaVita Inc.', Code: 'DVA' },
        { StockName: 'DVA', Code: 'DVA' },
        { StockName: 'Mohawk Industries Inc.', Code: 'MHK' },
        { StockName: 'MHK', Code: 'MHK' },
        { StockName: 'Fox Corporation Class B', Code: 'FOX' },
        { StockName: 'FOX', Code: 'FOX' },
        { StockName: 'Ralph Lauren Corporation Class A', Code: 'RL' },
        { StockName: 'RL', Code: 'RL' },
        { StockName: 'Vornado Realty Trust', Code: 'VNO' },
        { StockName: 'VNO', Code: 'VNO' },
        { StockName: 'DISH Network Corporation Class A', Code: 'DISH' },
        { StockName: 'DISH', Code: 'DISH' },
        { StockName: 'News Corporation Class B', Code: 'NWS' },
        { StockName: 'NWS', Code: 'NWS' },];

    const fields = { value: 'StockName' };
    const { currentMode} = useStateContext();
    const textColor = currentMode === 'Light' ? 'black':'white';

    return (
        //<div >
        <AutoCompleteComponent id="atcelement" dataSource={searchData} fields={fields} placeholder="Find a stock" highlight={true}/>
    )
}

export default Search